engines:
  fixme:
    enabled: true
  markdownlint:
    enabled: true
  checkstyle:
    enabled: true
    config: 
      file: config/checkstyle/checkstyle.xml
  pmd:
    enabled: true
    config: 
      file: config/pmd/pmd.xml
ratings:
  paths:
  - src/**
  - "**.java"
  - "**.md"
  - "**.xml"
  - "**.properties"
exclude_paths:
- docs/**/*
- "**.prog"
- "**.plang"
